CREATE TABLE IF NOT EXISTS Genres (
	id SERIAL PRIMARY KEY,
	name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS Performer (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	genre_id INTEGER NOT NULL REFERENCES Genres(id)
);

CREATE TABLE IF NOT EXISTS Album (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	edition_year CHAR(4) NOT NULL,
	performer_id INTEGER NOT NULL REFERENCES Performer(id)
);

CREATE TABLE IF NOT EXISTS Tracks (
	id BIGSERIAL PRIMARY KEY,
	track_name VARCHAR(120) NOT NULL,
	performer_id INTEGER NOT NULL REFERENCES Performer(id),
	album_id INTEGER NOT NULL REFERENCES Album(id),
	duration NUMERIC NOT NULL
);

